### ISSUE TITLE
Error message when searching in browser

### ISSUE THREAD

**Issue by lro77** [jefdongus/insert-symbols-anki-addon#18]
When I'm doing a text search in the browser, I get the following error message whenever I input any character. Do you have an ideas for how to go about fixing this?

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-07-07 08:10:47

Caught exception:
RuntimeError: wrapped C/C++ object of type QComboBox has been deleted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\eller\AppData\Roaming\Anki2\addons21\2040501954\browser_replacer.py", line 46, in on_text_edited
    self._check_for_replacement(current_text, False)
  File "C:\Users\eller\AppData\Roaming\Anki2\addons21\2040501954\browser_replacer.py", line 63, in _check_for_replacement
    search_box = self.get_search_box()
SystemError: PyEval_EvalFrameEx returned a result with an error set

**Comment by thiswillbeyourgithub** [comment]
Do you happen to use the addon "openning the same window multiple times"?

Does this happend always or only sometimes?

**Comment by lro77** [comment]
I do also have that addon. This doesn't seem to happen all the time, only sometimes, and I'm not sure what I'm doing differently that is responsible for why.

**Comment by thiswillbeyourgithub** [comment]
(I'm not related to the creator of the addon btw)

This seems to be the same as #9 

To reproduce : open 2 browser windows, close one of them, try to search using the one that's still open. Apparently that causes this issue.

The only workaround I know of is to stop using several browsers or not close them.

**Comment by coco1602** [comment]
Yes, same issue. Sad there isn't any walkaround
