### ISSUE TITLE
Not working on 2.1.41 or higher

### ISSUE THREAD

**Issue by Bortex19** [jefdongus/insert-symbols-anki-addon#22]
@jefdongus Thank you very much.

It just does nothing.

Anki 2.1.41 (312fa278) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-06 14:25:25

Caught exception:
Traceback (most recent call last):
File "aqt\webview.py", line 36, in cmd
File "aqt\webview.py", line 135, in _onCmd
File "aqt\webview.py", line 580, in _onBridgeCmd
File "aqt\toolbar.py", line 169, in _linkHandler
File "aqt\toolbar.py", line 187, in _browseLinkHandler
File "aqt\main.py", line 1067, in onBrowse
File "aqt\__init__.py", line 101, in open
File "<decorator-gen-46>", line 2, in __init__
File "anki\hooks.py", line 89, in decorator_wrapper
File "anki\hooks.py", line 81, in repl
TypeError: on_browser_init() takes 3 positional arguments but 5 were given

**Comment by jefdongus** [comment]
Should be working when adding cards/editing cards in the card browser (inserting symbols into the card browser search bar is not working yet).
