### ISSUE TITLE
When loading Symbols As You Type is crashing while startup

### ISSUE THREAD

**Issue by demon1919** [jefdongus/insert-symbols-anki-addon#46]
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-07 09:49:24

When loading Symbols As You Type:
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "C:\Users\dsaka\AppData\Roaming\Anki2\addons21\2040501954\__init__.py", line 1, in <module>
    from . import insert_symbols
  File "C:\Users\dsaka\AppData\Roaming\Anki2\addons21\2040501954\insert_symbols.py", line 20, in <module>
    from .symbol_window import SymbolWindow
  File "C:\Users\dsaka\AppData\Roaming\Anki2\addons21\2040501954\symbol_window.py", line 19, in <module>
    from .Ui_SymbolWindow import Ui_SymbolWindow
  File "C:\Users\dsaka\AppData\Roaming\Anki2\addons21\2040501954\Ui_SymbolWindow.py", line 9, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

**Comment by jefdongus** [comment]
New version compatible with Anki 23.10
