### ISSUE TITLE
Update addon to work with new version 23.10

### ISSUE THREAD

**Issue by shmuelsash** [jefdongus/insert-symbols-anki-addon#47]
### Debug info

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-14 12:28:52

When loading Symbols As You Type:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\2040501954\__init__.py", line 1, in <module>
    from . import insert_symbols
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\2040501954\insert_symbols.py", line 20, in <module>
    from .symbol_window import SymbolWindow
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\2040501954\symbol_window.py", line 19, in <module>
    from .Ui_SymbolWindow import Ui_SymbolWindow
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\2040501954\Ui_SymbolWindow.py", line 9, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

![image](https://github.com/jefdongus/insert-symbols-anki-addon/assets/35056305/cac725ee-8dac-40c2-9136-9ebc14cf8f34)

**Comment by Aydamari** [comment]
Same here. It began a few days/weeks ago.

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.38
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-23 06:00:33

When loading Symbols As You Type:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/home/portufaria/.var/app/net.ankiweb.Anki/data/Anki2/addons21/2040501954/__init__.py", line 1, in <module>
    from . import insert_symbols
  File "/home/portufaria/.var/app/net.ankiweb.Anki/data/Anki2/addons21/2040501954/insert_symbols.py", line 20, in <module>
    from .symbol_window import SymbolWindow
  File "/home/portufaria/.var/app/net.ankiweb.Anki/data/Anki2/addons21/2040501954/symbol_window.py", line 19, in <module>
    from .Ui_SymbolWindow import Ui_SymbolWindow
  File "/home/portufaria/.var/app/net.ankiweb.Anki/data/Anki2/addons21/2040501954/Ui_SymbolWindow.py", line 9, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

**Comment by maxwellconolly** [comment]
I am also getting the same issue. 

Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-26 10:59:48

When loading Symbols As You Type:
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "C:\Users\maxwe\AppData\Roaming\Anki2\addons21\2040501954\__init__.py", line 1, in <module>
    from . import insert_symbols
  File "C:\Users\maxwe\AppData\Roaming\Anki2\addons21\2040501954\insert_symbols.py", line 20, in <module>
    from .symbol_window import SymbolWindow
  File "C:\Users\maxwe\AppData\Roaming\Anki2\addons21\2040501954\symbol_window.py", line 19, in <module>
    from .Ui_SymbolWindow import Ui_SymbolWindow
  File "C:\Users\maxwe\AppData\Roaming\Anki2\addons21\2040501954\Ui_SymbolWindow.py", line 9, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

**Comment by juan94c** [comment]
Same here

When loading Symbols As You Type:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/juan/Library/Application Support/Anki2/addons21/2040501954/__init__.py", line 1, in <module>
    from . import insert_symbols
  File "/Users/juan/Library/Application Support/Anki2/addons21/2040501954/insert_symbols.py", line 20, in <module>
    from .symbol_window import SymbolWindow
  File "/Users/juan/Library/Application Support/Anki2/addons21/2040501954/symbol_window.py", line 19, in <module>
    from .Ui_SymbolWindow import Ui_SymbolWindow
  File "/Users/juan/Library/Application Support/Anki2/addons21/2040501954/Ui_SymbolWindow.py", line 9, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

**Comment by jefdongus** [comment]
New version compatible with Anki 23.10
