### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by dilano-keats** [jefdongus/insert-symbols-anki-addon#48]
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-09 13:25:18

When loading Symbols As You Type:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\dilan\AppData\Roaming\Anki2\addons21\2040501954\__init__.py", line 1, in <module>
    from . import insert_symbols
  File "C:\Users\dilan\AppData\Roaming\Anki2\addons21\2040501954\insert_symbols.py", line 20, in <module>
    from .symbol_window import SymbolWindow
  File "C:\Users\dilan\AppData\Roaming\Anki2\addons21\2040501954\symbol_window.py", line 19, in <module>
    from .Ui_SymbolWindow import Ui_SymbolWindow
  File "C:\Users\dilan\AppData\Roaming\Anki2\addons21\2040501954\Ui_SymbolWindow.py", line 9, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

**Comment by jefdongus** [comment]
New version compatible with Anki 23.10
