### ISSUE TITLE
"anki encountered a problem" error, symbols as you type "possibly involved"

### ISSUE THREAD

**Issue by jhkotnik** [jefdongus/insert-symbols-anki-addon#52]
Appears to cause the anki review screen to gray out after editing a card and exiting the edit window. Has also caused anki to crash once, but that does not seem to be the main problem.

debug info copied below:

Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.5-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.main", line 278, in on_focus_changed
  File "_aqt.hooks", line 3460, in __call__
  File "aqt.main", line 861, in on_focus_did_change
  File "aqt.reviewer", line 203, in refresh_if_needed
  File "aqt.reviewer", line 261, in nextCard
  File "aqt.reviewer", line 404, in _showQuestion
  File "_aqt.hooks", line 4258, in __call__
  File "/Users/jh_pro/Library/Application Support/Anki2/addons21/2040501954/insert_symbols.py", line 143, in on_reviewer_show_qa
    webview = ins_sym_webview_owners['reviewer'].web
AttributeError: 'NoneType' object has no attribute 'web'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2024-08-05T07:24, 'None', mod]
Advanced Browser ['874215009', 2024-10-27T07:20, 'None', mod]
AnKing Note Types Easy Customization ['952691989', 2024-10-21T07:29, 'None', mod]
AnkiHub ['1322529746', 2024-12-23T11:50, 'None', mod]
Batch Editing ['291119185', 2023-10-25T17:38, 'None', '']
BetterSearch ['1052724801', 2024-03-06T08:25, 'None', mod]
Browser Resizer ['1435775540', 2023-11-11T09:16, 'None', mod]
Clickable tags updated ['clickable_tags_updated', 0, 'None', '']
Contanki - Controller Support for Anki beta ['1898790263', 2024-02-29T17:22, 'v1.0.2', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T18:19, 'None', mod]
Customize Keyboard Shortcuts ['24411424', 2023-11-01T02:17, 'None', mod]
Delay Overdue Cards ['43919973', 2024-01-30T17:12, 'None', '']
Edit Field During Review Cloze ['385888438', 2024-11-16T02:23, '6.21', mod]
Exam Notifier ['236593452', 2023-01-19T09:12, 'None', '']
Extended Card Stats During Review ['1008566916', 2024-02-26T11:07, 'None', '']
Extended Tag AddEdit Dialog ['1135507717', 2023-11-11T08:58, 'None', mod]
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-12-07T03:00, 'None', '']
Fastbar- with nightmode support ['46611790', 2023-06-27T04:47, 'None', '']
Find cards from UWorld test ['444814983', 2024-07-18T23:19, 'None', '']
Free Weekend - or Any Other Day ['742185195', 2020-04-10T04:57, 'None', mod]
Highlight Search Results in the Browser ['225180905', 2023-10-21T12:17, 'None', '']
Hint Hotkeys ['1844908621', 2023-04-14T07:13, 'None', '']
Image Editor ['307397307', 2022-09-07T21:09, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T00:15, 'None', '']
Mini Format Pack ['295889520', 2023-11-02T11:00, 'None', '']
More Decks Stats and Time Left ['1556734708', 2024-08-19T15:49, 'None', mod]
More Overview Stats 21 ['738807903', 2024-08-22T02:14, 'None', mod]
Pop-up Dictionary beta ['153625306', 2019-03-23T10:32, 'None', '']
Progress Bar ['2091361802', 2019-03-02T18:27, 'None', '']
Reset Ease ['947935257', 2023-11-11T17:22, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T18:43, 'None', '']
Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2022-08-15T00:22, 'None', mod]
Special Fields ['1102281552', 2024-10-26T08:51, 'None', mod]
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T03:24, 'None', mod]
Symbols As You Type ['2040501954', 2024-01-19T21:42, 'None', '']
Symbols ['1461102936', 2024-02-10T08:53, 'None', mod]
The KING of Button Add-ons ['374005964', 2024-09-23T05:14, 'None', '']
Wrapper meta-addon ['396502676', 2024-06-10T03:00, 'None', '']
rebuildempty some or all filtered decks ['104518886', 2023-05-16T15:33, 'None', '']

===IDs of active AnkiWeb add-ons===
1008566916 104518886 1046608507 1052724801 1102281552 1135507717 1210908941 1322529746 1374772155 1435775540 1461102936 153625306 1556734708 1771074083 1781298089 1844908621 1898790263 2040501954 2091361802 225180905 236593452 24411424 291119185 295889520 307397307 374005964 385888438 396502676 43919973 444814983 46611790 738807903 742185195 759844606 874215009 947935257 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add Hyperlink ['318752047', 2023-06-18T04:39, 'None', '']
Additional Card Fields Fork for 21 ['744725736', 2022-10-23T03:10, 'None', mod]
Advanced Card Styles ['1625103157', 2021-12-28T09:49, 'None', '']
Anki Simulator ['817108664', 2023-11-06T09:26, 'None', '']
Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-25T14:11, 'None', mod]
Clickable Tags v20 ['1739176371', 2022-01-30T14:58, 'None', '']
Closet For Anki ['272311064', 2022-08-12T01:27, 'None', '']
Cloze Overlapper for Anki 21 ['109531687', 2021-01-11T19:12, 'None', '']
Export Single Tag For Sharing ['960563361', 2022-04-10T14:30, 'None', '']
Google Translate ['1536291224', 2024-12-09T13:39, 'None', '']
High Yield Tags ['1918380616', 2023-01-10T11:14, 'None', mod]
Load Balanced Scheduler ['208879074', 2019-07-23T19:37, 'None', '']
Puppy Reinforcement ['1722658993', 2023-11-16T04:59, 'None', '']
Quick Colour Changing ['2491935955', 2023-10-18T20:15, 'None', mod]
Straight Reward ['957961234', 2023-11-01T07:11, 'None', '']
Syllabus - Anki Statistics and Export by Tag and Deck ['668156440', 2020-01-19T11:52, 'None', mod]
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-17T11:28, 'None', mod]
add-on dialog searchfilter bar ['561945101', 2023-10-18T09:22, 'None', '']

**Comment by Dann15** [comment]
same thing today

**Comment by Al-0786** [comment]
I am having the same issue

**Comment by Sabicool** [comment]
@jhkotnik Have created a pull request that solves that issue. Hopefully @jefdongus can review the changes and merge the pull request

**Comment by puckdoc** [comment]
Have same issue. Very annoying

Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-15.1.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.main", line 278, in on_focus_changed
  File "_aqt.hooks", line 3460, in __call__
  File "aqt.main", line 861, in on_focus_did_change
  File "aqt.reviewer", line 203, in refresh_if_needed
  File "aqt.reviewer", line 261, in nextCard
  File "aqt.reviewer", line 404, in _showQuestion
  File "_aqt.hooks", line 4258, in __call__
  File "/Users/christianhoward/Library/Application Support/Anki2/addons21/2040501954/insert_symbols.py", line 143, in on_reviewer_show_qa
    webview = ins_sym_webview_owners['reviewer'].web
AttributeError: 'NoneType' object has no attribute 'web'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2024-08-05T10:24, 'None', mod]
Add Table ['1237621971', 2023-06-18T07:37, 'None', mod]
Advanced Browser ['874215009', 2024-10-27T10:20, 'None', '']
AnKing Note Types Easy Customization ['952691989', 2024-10-21T10:29, 'None', mod]
AnkiConnect ['2055492159', 2024-11-06T20:34, 'None', mod]
AnkiHub ['1322529746', 2024-12-23T14:50, 'None', '']
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-12-05T20:28, 'None', '']
BetterSearch ['1052724801', 2024-03-06T11:25, 'None', '']
Closet For Anki ['272311064', 2022-08-12T04:27, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T11:06, 'None', '']
Contanki - Controller Support for Anki beta ['1898790263', 2024-02-29T20:22, 'v1.0.2', mod]
Enhanced Cloze for Anki 21 ['1990296174', 2023-09-10T14:48, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2025-01-04T02:12, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T07:47, 'None', '']
Filtered Deck From Tag ['2058067048', 2023-02-18T20:42, 'None', '']
Image Occlusion Enhanced for Anki 21 ['1374772155', 2022-04-09T03:15, 'None', '']
ImageResizer ['1214357311', 2023-12-02T20:58, 'None', '']
Quick Colour Changing ['2491935955', 2023-10-18T23:15, 'None', mod]
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']
Symbols As You Type ['2040501954', 2024-01-20T00:42, 'None', '']
The KING of Study Timers ['907028815', 2022-04-20T14:14, 'None', mod]
True Retention ['613684242', 2017-11-19T15:43, 'None', '']
uworld_qid_to_anki_search ['607963104', 2023-09-21T11:18, 'None', mod]

===IDs of active AnkiWeb add-ons===
1052724801 1214357311 1237621971 1322529746 1374772155 1436550454 1771074083 1898790263 1990296174 2040501954 2055492159 2058067048 2491935955 272311064 46611790 594329229 607963104 613684242 759844606 874215009 907028815 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T21:19, 'None', '']
Exam Notifier ['236593452', 2023-01-19T12:12, 'None', '']
Special Fields ['1102281552', 2024-10-26T11:51, 'None', '']
Zzz not maintained  may not work Improved Quizlet to Anki 21 Importer ['538351043', 2020-11-14T21:16, 'None', '']
