### ISSUE TITLE
Error when searching in browser (?emojis)

### ISSUE THREAD

**Issue by jamiekoi** [jefdongus/insert-symbols-anki-addon#7]
I get this error, every time I search my tags. I think this only occurs if the tag/deck that has an **emoji** in its name. for example,
in the browser's search bar: ("deck:💊Pharmacology" _keyword_) or any tag with an emoji in its name.

This only occured with the latest 2 updates to your add-on. Never had any problem with like this with the previous updates before the last 2

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.3
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-07 11:33:37
Add-ons possibly involved: Symbols As You Type

Caught exception:
Traceback (most recent call last):
  File "/Users/jamiekoi/Library/Application Support/Anki2/addons21/2040501954/browser_replacer.py", line 32, in on_text_edited
    self._check_for_replacement(current_text, False)
  File "/Users/jamiekoi/Library/Application Support/Anki2/addons21/2040501954/browser_replacer.py", line 56, in _check_for_replacement
    is_whitespace_pressed = self._is_whitespace(text, cursor_pos-1)
  File "/Users/jamiekoi/Library/Application Support/Anki2/addons21/2040501954/browser_replacer.py", line 41, in _is_whitespace
    return string[i].isspace()
IndexError: string index out of range

Caught exception:
Traceback (most recent call last):
  File "/Users/jamiekoi/Library/Application Support/Anki2/addons21/2040501954/browser_replacer.py", line 32, in on_text_edited
    self._check_for_replacement(current_text, False)
  File "/Users/jamiekoi/Library/Application Support/Anki2/addons21/2040501954/browser_replacer.py", line 56, in _check_for_replacement
    is_whitespace_pressed = self._is_whitespace(text, cursor_pos-1)
  File "/Users/jamiekoi/Library/Application Support/Anki2/addons21/2040501954/browser_replacer.py", line 41, in _is_whitespace
    return string[i].isspace()
IndexError: string index out of range

**Comment by jefdongus** [comment]
Ok, it shouldn't crash anymore. Symbol insertion in the search bar is currently not supported when there are emojis (or certain other Unicode characters) but should still work for most other characters.

**Comment by jamiekoi** [comment]
Thanks for your quick fix! This did it.
